### ISSUE TITLE
Allow the option to simply ensure/check if namespace is created

### ISSUE THREAD

**Issue by ansiblejunky** [redhat-cop/tower_utilities#158]
# Summary

The code in the `initialization.yml` task file attempts to create the namespace, but not all OpenShift configurations are setup where the team/user can do anything. In my current situation, the user does not have the ability to create namespaces and this permission is granted to OCP admins and not all users.

As a result, the following task fails but it should fail if the namespace does not exist, but succeed if already existing. Note that, I believe the reason it fails is because the template yaml only contains the name parameter for the Namespace, whereas the existing namespace that was created by the OCP Admins already, has a bunch of properties set on that. So the "Desired state" mechanism of Ansible is probably trying to replace that object with the simpler one defined by the template. This is another reason I want the ability to just check if a namespace exists with the same name - and not attempt to create one in OCP.  This is only to ensure the pre-req exists (namespace).

https://github.com/redhat-cop/aap_utilities/blob/ecf367a30a7f3884a32c2241aae980a7a893511b/roles/aap_ocp_install/tasks/initialization.yml#L11-L21

# Issue Type

- Bug Report

# Ansible, Collection, Docker/Podman details

```console (paste below)
ansible --version

ansible-galaxy collection list

podman --version

```

- ansible installation method: one of source, pip, OS package, EE

# OS / ENVIRONMENT

# Desired Behavior

# Actual Behavior

Please give some details of what is actually happening.
Include a [minimum complete verifiable example] with:

- playbook / task
- configuration file / list
- error

```console (error)

```

# STEPS TO REPRODUCE

```yaml (playbook/task)

```

```yaml (config/list/array/variables)

```

[minimum complete verifiable example]: http://stackoverflow.com/help/mcve

**Comment by ansiblejunky** [comment]
It appears the problem was actually that the properties were all different in the target OCP. 
This is what I ended up doing outside of the role - which uses the newer format of parameters:

```
  - name: Ensure namespace exists
    kubernetes.core.k8s:
      host: "{{ __aap_ocp_install_auth_results['openshift_auth']['host'] }}"
      api_key: "{{ __aap_ocp_install_auth_results['openshift_auth']['api_key'] }}"
      validate_certs: "{{ aap_ocp_install_ocp_connection['validate_certs'] | default(omit) }}"
      state: present
      name: "{{ aap_ocp_install_namespace }}"
      api_version: project.openshift.io/v1
      kind: Project
```
