### ISSUE TITLE
Incorrect installation setup bundle extracted and configured

### ISSUE THREAD

**Issue by snagoor** [redhat-cop/tower_utilities#199]
# Summary

`infra.aap_utilities.aap_setup_download` downloads 2 different setup types 

1. ansible-automation-platform-containerized-setup-2.4-1.tar.gz
2. ansible-automation-platform-setup-2.4-2.tar.gz

# Issue Type

- Bug Report

# Ansible, Collection, Docker/Podman details

```console (paste below)
ansible --version
ansible [core 2.14.2]
  config file = /root/aap/aap_standalone/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.2 (main, May 24 2023, 00:00:00) [GCC 11.3.1 20221121 (Red Hat 11.3.1-4)] (/usr/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True

ansible-galaxy collection list

# /root/.ansible/collections/ansible_collections
Collection            Version
--------------------- -------
ansible.posix         1.5.4  
awx.awx               23.0.0 
community.crypto      2.15.1 
community.general     7.3.0  
infra.aap_utilities   2.3.0  
kubernetes.core       2.4.0  
nshaik.aap_collection 1.0.14 

podman --version
podman version 4.4.1

```

- ansible installation method: one of source, pip, OS package, EE

# OS / ENVIRONMENT

Ansible Controller installation on RHEL 9.2 version

# Desired Behavior

Installation inventory file should be configured in the correct installation bundle extracted folder

# Actual Behavior

Installation bundle extracted and inventory file is configured in wrong location `/var/tmp/ansible-automation-platform-containerized-setup-2.4-1/` where the correct collection  should be `/var/tmp/ansible-automation-platform-setup-2.4-2/`

```console (error)

```

# STEPS TO REPRODUCE

Sample variable file that was used to call `infra.aap_utilities.aap_setup_download` role
```
aap_setup_down_offline_token: "xxxxeyJhbGciOixxxx"
aap_setup_down_version: "2.4"
aap_setup_down_type: "setup"
aap_setup_rhel_version: "9"
aap_setup_prep_inv_nodes:
  automationcontroller:
    - controller.example.com
aap_setup_prep_inv_vars:
  automationcontroller: # denotes the automation controller nodes as hybrid nodes (controller and execution)
    node_type: hybrid
    ignore_preflight_errors: true
  all:
    pg_database: "awx"
    pg_username: "awx"
    pg_sslmode: "prefer"  # set to 'verify-full' for client-side enforced SSL
    registry_url: "registry.redhat.io"
    receptor_listener_port: 27199
aap_setup_prep_inv_secrets:
  all:
    registry_username: "myregistry_user"
    registry_password: "changeme"
    admin_password: "changeme"
    pg_password: "changeme"
controller_validate_certs: false
```

This caused the the `infra.aap_utilities.aap_setup_install` role to fail with the following error

```
TASK [infra.aap_utilities.aap_setup_install : Run the Ansible Automation Platform setup program] ***
task path: /root/.ansible/collections/ansible_collections/infra/aap_utilities/roles/aap_setup_install/tasks/main.yml:72
ASYNC FAILED on controller: jid=439834133810.20100
fatal: [controller]: FAILED! => {"ansible_job_id": "439834133810.20100", "changed": false, "cmd": "./setup.sh -i inventory", "finished": 1, "msg": "[Errno 2] No such file or directory: b'./setup.sh'", "rc": 2, "results_file": "/root/.ansible_async/439834133810.20100", "started": 1, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
```

[minimum complete verifiable example]: http://stackoverflow.com/help/mcve

**Comment by snagoor** [comment]
Changing the code to add an additional conditional as below helped me move past the error that was reported here. 

`~/.ansible/collections/ansible_collections/infra/aap_utilities/roles/aap_setup_download/tasks/main.yml`

```
- name: Downloading the latest installer of type {{ aap_setup_down_type }}
  ansible.builtin.get_url:
    url: "{{ item.downloadHref }}"
    dest: "{{ aap_setup_down_dest_dir }}/{{ item.filename }}"
    mode: 0644
    headers:
      Authorization: "Bearer {{ __aap_setup_down_login.json.access_token }}"
  loop: "{{ __aap_setup_down_images[:3] }}"
  when: 
    - ((aap_setup_down_type | string) + '-' + (aap_setup_down_version | string)) in item.filename
    - not 'containerized-setup' in item.filename
  register: __aap_setup_down_downloads
```
