### ISSUE TITLE
aap_setup_download does not fetch setup-bundle from Red Hat

### ISSUE THREAD

**Issue by drshawnkwang** [redhat-cop/tower_utilities#242]
# Summary

The aap_utilities role aap_setup_download is broken. Red Hat may have changed how AAP setup bundles are downloaded, see https://access.redhat.com/solutions/7013662. 

# Issue Type

- Bug Report

# Ansible, Collection, Docker/Podman details

```console (paste below)
ansible --version

ansible [core 2.16.6]
  config file = /home/skwang/esnet/git/aap-manager/ansible.cfg
  configured module search path = ['/home/skwang/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/skwang/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.9 (main, Apr 10 2024, 13:16:36) [GCC 13.2.0] (/usr/bin/python3)
  jinja version = 3.1.3
  libyaml = True


ansible-galaxy collection list

Collection                               Version
---------------------------------------- -------
ansible.posix                            1.5.4  
citrix.adc                               1.3.0  
community.docker                         3.8.0  
community.general                        8.5.0  
community.library_inventory_filtering_v1 1.0.0  
community.vmware                         4.2.0  
containers.podman                        1.10.3 
esnet.common                             0.0.4  
infra.aap_utilities                      2.5.1  
infra.controller_configuration           2.7.1  
kubernetes.core                          2.4.0  
netscaler.adc                            2.5.1  
redhat_cop.controller_configuration      2.2.5  

podman --version

podman version 4.9.4
```

- ansible installation method: one of source, pip, OS package, EE
- Ansible installed using Debian .deb package

# OS / ENVIRONMENT

# Desired Behavior

Role should download AAP Setup-bundle tarball.

# Actual Behavior

Please give some details of what is actually happening.
Include a [minimum complete verifiable example] with:

- playbook / task
- configuration file / list
- error

```console (error)

```

See below for details.

# STEPS TO REPRODUCE

Run a playbook with aap.utilities.app_setup_download with `aap_setup_down_offline_token`.

```yaml (playbook/task)
---
# code: language=ansible
- name: Min-verifiable-playbook
  gather_facts: false
  hosts: localhost
  connection: localhost
  strategy: linear
  vars:
    aap_setup_down_version: 2.4
    aap_setup_rhel_version: 8
    aap_setup_down_dest_dir: /tmp
  tasks:
    - name: Setup - Download files
      ansible.builtin.import_role:
        name: infra.aap_utilities.aap_setup_download
```

```yaml (config/list/array/variables)
aap_setup_down_offline_token = (redacted)
aap_setup_down_version: 2.4
aap_setup_rhel_version: 8
aap_setup_working_dir: /tmp
```

See https://gist.github.com/drshawnkwang/5371528e14a1ac2d19f0322ec5d20298

I have pasted the output of `ansible-playbook -vvv playbooks/mvp.yml`. I have included in the gist the most-relevant output. When the role aap_setup_download runs https://github.com/redhat-cop/aap_utilities/blob/devel/roles/aap_setup_download/tasks/main.yml#L27 - it tries to download the URL: `https://api.access.redhat.com/management/v1/images/d8587a2835877d6f6323eba49fb9486ce6b83cb7782c47951215a6f9de463de6/download` from RH API access. It receives a status code 304.

When I try to run download the above <URI> with `curl` (after obtaining an access token using the same offline-token) I get a redirect. If I use `curl -L <URI>`, as instructed in https://access.redhat.com/solutions/7013662, I correctly download the file.

Thus Red Hat's changes may now require the ansible automation to follow the redirect in the same way that `curl -L` does.

[minimum complete verifiable example]: http://stackoverflow.com/help/mcve
