### ISSUE TITLE
The role infra.aap_utilities.aap_setup_install won't pick up a successful execution of setup.sh

### ISSUE THREAD

**Issue by itzome** [redhat-cop/tower_utilities#265]
## Summary

The role infra.aap_utilities.aap_setup_install won't pick up a successful execution of setup.sh and keeps polling for the full async duration (>2h).

## Issue Type

- Bug Report

## Ansible, Collection, Docker/Podman details

```console (paste below)
ansible --version
ansible [core 2.17.4]
  config file = None
  configured module search path = ['/app/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /app/.local/lib/python3.11/site-packages/ansible
  ansible collection location = /app/.ansible/collections:/usr/share/ansible/collections
  executable location = /app/.local/bin/ansible
  python version = 3.11.8 (main, Feb 19 2024, 22:58:08) [GCC 12.2.1 20220924] (/usr/bin/python3)
  jinja version = 3.1.4
  libyaml = True

ansible-galaxy collection list
Collection                               Version
---------------------------------------- -------
ansible.posix                            1.6.2  
community.general                        10.2.0 
infra.aap_utilities                      2.5.2
community.docker                         3.10.3 
community.general                        9.0.1  
containers.podman                        1.13.0 
kubernetes.core                          3.1.0
```

- ansible installation method: pip

## OS / ENVIRONMENT

Playbooks are running in gitlab CI. But the error is reproducable outside as well.

## Desired Behavior

Role should continue after the setup.sh successfully finishes.

## Actual Behavior

Role configures AAP correctly but never finishes the configuration playbook run

- playbook / task
https://github.com/redhat-cop/aap_utilities/blob/devel/roles/aap_setup_install/tasks/setup.yml

- error
playbook runs into timeout after 10000 seconds (async amount)

```console (error)
TASK [infra.aap_utilities.aap_setup_install : Run the Ansible Automation Platform setup program] ***
ASYNC POLL on ansible-xxx: jid=j535819395173.439 started=1 finished=0
ASYNC POLL on ansible-xxx: jid=j535819395173.439 started=1 finished=0
ASYNC POLL on ansible-xxx: jid=j535819395173.439 started=1 finished=0
ASYNC POLL on ansible-xxx: jid=j535819395173.439 started=1 finished=0
```

```console (error)
runner-xxx:~$ ls -al .ansible_async/j535819395173.439 
-rw-r--r--    1 ansible  ansible    2058474 Jan 13 13:33 .ansible_async/j535819395173.439
runner-xxx:~$ 
```

At the end of this file it confirms the run was successful:

```console (error)
The setup process completed successfully.
Setup log saved to /var/log/tower/setup-2025-01-13-13:26:15.log.
```

## STEPS TO REPRODUCE

Import the aap_setup_install Role into a playbook 

```yaml (playbook/task)
    - name: Install AAP and configure certificates
      block:
        - name: Import infra.aap_utilities.aap_setup_install  # noqa: run-once[task]
          delegate_to: localhost
          run_once: true
          ansible.builtin.import_role:
            name: infra.aap_utilities.aap_setup_install
```

```yaml (config/list/array/variables)

```

[minimum complete verifiable example]: http://stackoverflow.com/help/mcve

**Comment by djdanielsson** [comment]
what version of AAP are you trying to install?

**Comment by itzome** [comment]
version 2.4-7 is currently deployed

**Comment by itzome** [comment]
After using -vvv with the playbook it showed, that the problem was that the python version on the controller node that got picked up by the playbook, which was 3.9, and the python version in my gitlab runner, which was 3.11, caused the async_status.py module to not execute since the interpreter in the file was modified automatically to 3.9. 
no further errors were shown but the task ran into the timeout

I fixed this doing this when importing the rol

```yaml (playbook/task)    
 - name: Import infra.aap_utilities.aap_setup_install  # noqa: run-once[task]
          delegate_to: localhost
          run_once: true
          vars:
            ansible_python_interpreter: /usr/bin/python3.11
          ansible.builtin.import_role:
            name: infra.aap_utilities.aap_setup_install
```
