### ISSUE TITLE
Update installation role(s) to handle AAP setup/bundle

### ISSUE THREAD

**Issue by ericzolf** [redhat-cop/tower_utilities#34]
Since AAP 1.2 is available from [access.redhat.com](https://access.redhat.com/downloads/content/480/ver=1.2/rhel---7/1.2/x86_64/product-software) under a new package name "ansible-automation-platform-setup-bundle-1.2.1-1", we need to find a way to cope with a different name of the package, not easily downloadable, so probably pre-downloaded.

**Comment by sean-m-sullivan** [comment]
I was able to do it via feeding it the link and specifying it before, it worked without a hitch, however I believe the link is only good for 30 minutes.
Here is the playbook. 
```
- name: Install Ansible Tower
  hosts: localhost
  become: true
  vars:
    tower_releases_url: https://access.cdn.redhat.com/content/origin/files/sha256/75/12345/ansible-automation-platform-setup-bundle-1.2.1-1.tar.gz?user=12345&_auth_=12345
    tower_setup_file: ansible-automation-platform-setup-bundle-1.2.1-1.tar.gz?user=12345&_auth_=12345
    tower_database_host: 192.168.122.120
    tower_hosts: []
    tower_ah_hosts:
      - 192.168.122.200
  roles:
    - sean_m_sullivan.tower_utilities.install
```
