### ISSUE TITLE
Add example implementation to prepare/install roles

### ISSUE THREAD

**Issue by Tompage1994** [redhat-cop/tower_utilities#88]
The roles don't really have an obvious example to follow for installing AAP. 

In particular it isn't obvious what needs to be set for `aap_setup_prep_inv_nodes` and `aap_setup_prep_inv_vars`. The readme does point to the [defaults](https://github.com/redhat-cop/aap_utilities/blob/devel/roles/aap_setup_prepare/defaults/main.yml) but that isn't really documentation.

Just adding to the example at the bottom of the prepare and install roles' readmes would be a good start here.

add something like:

```
...
vars:
  aap_setup_prep_inv_nodes:
    automationcontroller:
      autoctl1.example.com: 
      autoctl2.example.com: 
  aap_setup_prep_inv_vars:
    ...
```
